language: php

sudo: false

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 5.5
          env: deps=low
        - php: 5.5
        - php: 5.6
        - php: 7.0
          env: deps=low
        - php: 7.0
        - php: 7.1
        - php: hhvm
        - php: hhvm
          env: deps=low
        - php: nightly

before_script:
    - composer self-update
    - mkdir -p build/logs
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/coveralls --no-interaction
